task_name: "RelationExtraction"
data_path: "datasets"
dataset_name: "TACRED"
max_seq_length: 256
overwrite_cache: False
pad_to_max_length: False
num_tasks: 10
class_per_task: 4
use_prompt_input: False